### News
- **September 2019**: Presented my PhD research at [Utah Deep Learning meetup](https://www.meetup.com/Utah-Deep-Learning/events/263569154/).
- **May 2019**: Gave a talk at [ICRA 2019](www.icra2019.org) Workshop, [Benchmarking for Robotic Manipulation](http://www.ycbbenchmarks.com/ICRA2019_workshop) on Benchmarking Robotic In-Hand Manipulation.
- **April 2019**: Passed my PhD proposal!
- **March 2019**: Our [tactile force paper](./publication/tactile_force/) is a finalist for the Best Robot Manipulation Paper at ICRA 2019!
- **January 2019**: 3 papers accepted in ICRA 2019.
- **2018**: Papers accepted in [ICRA 2018](./publication/regrasp_planning/), [Autonomous Robots ](./publication/in_grasp_journal/) and [CoRL 2018](./publication/dope_corl/).
- **2017**: [Paper](./publication/in_grasp_manipulation/) accepted in RSS 2017.
