### News
- **April 2020**: Our work on in-hand dynamics inference in a factor graph is now online! [[URL](./publication/in_hand_dynamics/)]
- **March 2020**: Passed my PhD defense! [[thesis](./project/phd_thesis)]
- **January 2020**: [Reconstruction Grasping](./publication/merwe_grasp) paper accepted to ICRA 2020.
- **December 2019**: [Benchmarking In-Hand Manipulation](./publication/bih/) paper accepted to RA-L.
- **September 2019**: Invited talk on in-hand manipulation at [Utah DL meetup](https://www.meetup.com/Utah-Deep-Learning/events/263569154/).
- **ICRA 2019**: 3 papers accepted, [tactile force paper](./publication/tactileforce_icra/)--finalist for "Best Robot Manipulation Paper Award", and  invited talk on Benchmarking In-Hand manipulation at [Benchmarking for Robotic Manipulation workshop](http://www.ycbbenchmarks.com/ICRA2019_workshop).
