### News
- **RSS 2022**: Our work on [Correcting Robot Plans with Natural Language Feedback](./publication/robolang/) was accepted.
- **ICRA 2022**: Our efforts on improving human robot handovers had two papers accepted, [MPC for reactive human-robot handovers](./publication/handover_mpc/) and [HandoverSim](./publication/handoversim/). 
- **CoRL 2021**: Paper accepted with Oral Presentation - [STORM MPC leveraging GPU compute](./publication/storm).
- **2020**: Passed PhD Defense [[thesis](./project/phd_thesis)].
- **ICRA 2019**: 3 papers accepted, [tactile force paper](./publication/tactileforce_icra/)--finalist for "Best Robot Manipulation Paper Award", and  invited talk on Benchmarking In-Hand manipulation at [Benchmarking for Robotic Manipulation workshop](http://www.ycbbenchmarks.com/ICRA2019_workshop).
